behaviors:
  Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 400
      num_layers: 3
    module_settings:
      hidden_units : 225
      task_obs_dim: 11
      state_dim: 24
      latent_dim: 6
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0     
    keep_checkpoints: 200
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 60000
    checkpoint_interval : 500000