behaviors:
  Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 225
      num_layers: 3
    transfer_settings:
      use_bases: false
      hidden_units : 256
      base_in_path: "bases/models/Reacher/bases_dim_6/100k/aligned_00015/UR10_input.pth"
      base_out_path: "bases/models/Reacher/bases_dim_6/100k/aligned_00015/UR10_output.pth" 
      task_obs_dim: 10
      state_dim: 12
      latent_dim: 6
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0     
    keep_checkpoints: 200
    max_steps: 5000000
    time_horizon: 200
    summary_freq: 60000
    checkpoint_interval : 50000
